language: ruby

sudo: false

notifications:
  email: false
  
rvm:
- 2.3.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler

before_script:
  - npm install -g grunt-cli
  - npm install

script: ./test.sh
